import dynamic from 'next/dynamic';

export interface ThemeConfig {
  slug: string;
  name: string;
  description: string;
  thumbnail: string;
  accentColor: string;
  component?: React.ComponentType<any>;
}

export const themes: Record<string, ThemeConfig> = {
  apple: {
    slug: 'apple',
    name: 'Apple Keynote',
    description: 'Clean, cinematic scroll storytelling with giant typography.',
    thumbnail: '/assets/themes/apple-preview.jpg',
    accentColor: '#000000',
  },
  netflix: {
    slug: 'netflix',
    name: 'Netflix',
    description: 'A cinematic streaming platform experience for your portfolio.',
    thumbnail: '/assets/themes/netflix-preview.jpg',
    accentColor: '#E50914',
  },
  windows: {
    slug: 'windows',
    name: 'Windows 11',
    description: 'A complete desktop OS simulation with draggable windows.',
    thumbnail: '/assets/themes/windows-preview.jpg',
    accentColor: '#0078D4',
  },
  macos: {
    slug: 'macos',
    name: 'macOS Sonoma',
    description: 'A sleek, premium macOS desktop simulation with a Dock and Menu Bar.',
    thumbnail: '/assets/themes/macos-preview.jpg',
    accentColor: '#007AFF',
  },
  spotify: {
    slug: 'spotify',
    name: 'Spotify',
    description: 'A premium music player experience with dynamic playlists and a persistent Now Playing bar.',
    thumbnail: '/assets/themes/spotify-preview.jpg',
    accentColor: '#1DB954',
  },
  steam: {
    slug: 'steam',
    name: 'Steam',
    description: 'A PC gaming ecosystem. Your projects as games, skills as achievements, and profile as a gamer card.',
    thumbnail: '/assets/themes/steam-preview.jpg',
    accentColor: '#66c0f4',
  },
  playstation: {
    slug: 'playstation',
    name: 'PlayStation',
    description: 'A console gaming experience. Cross-Media Bar interface with immersive ambient backgrounds.',
    thumbnail: '/assets/themes/playstation-preview.jpg',
    accentColor: '#00439C',
  },
  jarvis: {
    slug: 'jarvis',
    name: 'JARVIS (Stark HUD)',
    description: 'Highly animated, futuristic, and cinematic voice-assistant AI interface.',
    thumbnail: '/assets/themes/jarvis-preview.jpg',
    accentColor: '#00f0ff',
  },
  ironman: {
    slug: 'ironman',
    name: 'Mark LXXXV HUD',
    description: 'A high-tech, tactical augmented reality interface inspired by Iron Man.',
    thumbnail: '/assets/themes/ironman-preview.jpg',
    accentColor: '#ff0000',
  },
  terminal: {
    slug: 'terminal',
    name: 'Hacker Terminal',
    description: 'A retro Cyberpunk CLI interface with CRT scanlines and terminal commands.',
    thumbnail: '/assets/themes/terminal-preview.jpg',
    accentColor: '#00ff41',
  },
  nasa: {
    slug: 'nasa',
    name: 'NASA Mission Control',
    description: 'A telemetry dashboard with launch sequences, radar, and aerospace data feeds.',
    thumbnail: '/assets/themes/nasa-preview.jpg',
    accentColor: '#1A5F7A',
  },
  spacex: {
    slug: 'spacex',
    name: 'SpaceX Interface',
    description: 'A sleek, modern, touchscreen aerospace UI with docking telemetry.',
    thumbnail: '/assets/themes/spacex-preview.jpg',
    accentColor: '#ffffff',
  },
  cockpit: {
    slug: 'cockpit',
    name: 'Sci-Fi Cockpit',
    description: 'An immersive 3D spaceship cockpit with a functional warp drive.',
    thumbnail: '/assets/themes/cockpit-preview.jpg',
    accentColor: '#00e5ff',
  },
  uber: {
    slug: 'uber',
    name: 'Uber Dashboard',
    description: 'A clean, map-centric professional interface modeled after ride-sharing apps.',
    thumbnail: '/assets/themes/uber-preview.jpg',
    accentColor: '#000000',
  },
  tesla: {
    slug: 'tesla',
    name: 'Tesla Dashboard',
    description: 'Sleek glassmorphism and 3D car interactions inspired by the Tesla dashboard.',
    thumbnail: '/assets/themes/tesla-preview.jpg',
    accentColor: '#E82127',
  },
  f1: {
    slug: 'f1',
    name: 'Formula 1 Race Control',
    description: 'An aggressive FIA race control layout tracking your telemetry data in real-time.',
    thumbnail: '/assets/themes/f1-preview.jpg',
    accentColor: '#ff1801',
  },
  airport: {
    slug: 'airport',
    name: 'Airport Departures Board',
    description: 'A nostalgic airport terminal featuring split-flap displays, boarding passes, and flight routes.',
    thumbnail: '/assets/themes/airport-preview.jpg',
    accentColor: '#FFB800',
  },
  classified: {
    slug: 'classified',
    name: 'Classified',
    description: 'Top secret restricted access terminal.',
    thumbnail: '/assets/themes/classified-preview.jpg',
    accentColor: '#000000',
  },
  maps: {
    slug: 'maps',
    name: 'Google Maps',
    description: 'Explore your portfolio as a geospatial map.',
    thumbnail: '/assets/themes/maps-preview.jpg',
    accentColor: '#1A73E8',
  },
  prison: {
    slug: 'prison',
    name: 'Prison / Jail Escape',
    description: 'A classified blueprint escape plan.',
    thumbnail: '/assets/themes/prison-preview.jpg',
    accentColor: '#0a3663',
  },
  detective: {
    slug: 'detective',
    name: 'Investigation Board',
    description: 'A chaotic corkboard filled with evidence, pins, and red string.',
    thumbnail: '/assets/themes/detective-preview.jpg',
    accentColor: '#d32f2f',
  },
  museum: {
    slug: 'museum',
    name: 'Museum Exhibition',
    description: 'A grand art gallery presenting your portfolio as priceless artifacts.',
    thumbnail: '/assets/themes/museum-preview.jpg',
    accentColor: '#d4af37',
  },
  library: {
    slug: 'library',
    name: 'Library of Knowledge',
    description: 'An ancient, dusty library with old parchment, scrolls, and leather bound tomes.',
    thumbnail: '/assets/themes/library-preview.jpg',
    accentColor: '#8b4513',
  },
  comic: {
    slug: 'comic',
    name: 'Interactive Comic Book',
    description: 'A vibrant pop-art comic book style layout with thick black borders, action bubbles, and halftone dots.',
    thumbnail: '/assets/themes/comic-preview.jpg',
    accentColor: '#e62e2d',
  },
  hotel: {
    slug: 'hotel',
    name: 'Luxury Hotel Booking',
    description: 'An elegant, high-end 5-star hotel experience featuring serif typography, gold accents, and spacious layouts.',
    thumbnail: '/assets/themes/hotel-preview.jpg',
    accentColor: '#d4af37',
  },
  minecraft: {
    slug: 'minecraft',
    name: 'Minecraft Inventory',
    description: 'A blocky, nostalgic 8-bit experience. Mine through the page to discover chests, crafting tables, and hidden diamonds.',
    thumbnail: '/assets/themes/minecraft-preview.jpg',
    accentColor: '#5a9e32',
  },
  rpg: {
    slug: 'rpg',
    name: 'RPG Game Menu',
    description: 'A classic 16-bit JRPG adventure. Equip scrolls, check your character stats, and defeat the final boss for contact info.',
    thumbnail: '/assets/themes/rpg-preview.jpg',
    accentColor: '#5577ff',
  },
  cinema: {
    slug: 'cinema',
    name: 'Movie Theatre Experience',
    description: 'Walk down the red carpet lobby, grab some concessions, and view your projects on the big screen.',
    thumbnail: '/assets/themes/cinema-preview.jpg',
    accentColor: '#b31b1b',
  },
  carnival: {
    slug: 'carnival',
    name: 'Carnival',
    description: 'A vibrant, whimsical carnival experience with tents, games, and bright lights.',
    thumbnail: '/assets/themes/carnival-preview.jpg',
    accentColor: '#ff00ff',
  },
  formal: {
    slug: 'formal',
    name: 'Formal Cultural Showcase',
    description: 'An elegant, highly interactive, physics-driven canvas showcasing cultural destinations.',
    thumbnail: '/images/formal/chinese_roof.png',
    accentColor: '#4A3B32',
  }
};

export const ThemeComponents: Record<string, React.ComponentType<any>> = {
  apple: dynamic(() => import('../themes/apple/Adapter')),
  netflix: dynamic(() => import('../themes/netflix/Adapter')),
  windows: dynamic(() => import('../themes/windows/Adapter')),
  macos: dynamic(() => import('../themes/macos/Adapter')),
  spotify: dynamic(() => import('../themes/spotify/Adapter')),
  steam: dynamic(() => import('../themes/steam/Adapter')),
  playstation: dynamic(() => import('../themes/playstation/Adapter')),
  jarvis: dynamic(() => import('../themes/jarvis/Adapter')),
  ironman: dynamic(() => import('../themes/ironman/Adapter')),
  terminal: dynamic(() => import('../themes/terminal/Adapter')),
  nasa: dynamic(() => import('../themes/nasa/Adapter')),
  spacex: dynamic(() => import('../themes/spacex/Adapter')),
  cockpit: dynamic(() => import('../themes/cockpit/Adapter')),
  uber: dynamic(() => import('../themes/uber/Adapter')),
  tesla: dynamic(() => import('../themes/tesla/Adapter')),
  f1: dynamic(() => import('../themes/f1/Adapter')),
  airport: dynamic(() => import('../themes/airport/Adapter')),
  classified: dynamic(() => import('../themes/classified/Adapter')),
  maps: dynamic(() => import('../themes/maps/Adapter')),
  prison: dynamic(() => import('../themes/prison/Adapter')),
  detective: dynamic(() => import('../themes/detective/Adapter')),
  museum: dynamic(() => import('../themes/museum/Adapter')),
  library: dynamic(() => import('../themes/library/Adapter')),
  comic: dynamic(() => import('../themes/comic/Adapter')),
  hotel: dynamic(() => import('../themes/hotel/Adapter')),
  minecraft: dynamic(() => import('../themes/minecraft/Adapter')),
  rpg: dynamic(() => import('../themes/rpg/Adapter')),
  cinema: dynamic(() => import('../themes/cinema/Adapter')),
  carnival: dynamic(() => import('../themes/carnival/Adapter')),
  formal: dynamic(() => import('../themes/formal/Adapter')),
};
